# 应用名称
spring:
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1356985444@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: wcwrrxzpoomejdbc
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  application:
    name: video

  servlet:
    multipart:
      max-file-size: 1073741824
      max-request-size: 1073741824
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 8
      # 最大活跃数
      max-active: 16
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 60000

#redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0


# mybatis配置
mybatis:
  check-config-location: true
  #  mybatis框架配置文件，对mybatis的生命周期起作用
  config-location: classpath:mybatis/config/mybatis-config.xml
  #  配置xml路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  #  配置model包路径
  type-aliases-package: com.yichen.video.model.*



# 应用服务 WEB 访问端口
server:
  port: 8080


#pagehelper:
#  offsetAsPageNum: true
#  rowBoundsWithCount: true
#  reasonable: true
#  returnPageInfo: true
#  params: count=countSql

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#存放视频的地址
resource:
  video-path: D:\bishe\video-repository\video
  picture-path: D:\bishe\video-repository\picture
  upload-path: D:\bishe\video-repository\upload
  avator-path: D:\bishe\video-repository\avator



